version: '3.3'

services:
  postgres:
    image: postgres:12
    volumes:
      - postgres_db:/home/postgresql/
      - postgres_db:/var/log/postgresql
    restart: always
    environment:
      - POSTGRES_USER=devops
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=wordpress
      - PGDATA=/home/postgresql/data
    ports:
      - 5432:5432
    networks:
      - wordpress
    logging:
      driver: journald


  wordpress:
    depends_on:
      - postgres
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: postgres:5432
      WORDPRESS_DB_USER: devops
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    networks:
      - wordpress
    logging:
      driver: journald

networks:
  wordpress:

volumes:
  postgres_db:
