version: '3.3'

services:
  postgres:
    image: postgres:12
    volumes:
      - postgres_db:/home/postgresql/
      - postgres_db:/var/log/postgresql
    restart: always
    environment:
      - POSTGRES_USER=devops
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=project
      - PGDATA=/home/postgresql/data
    ports:
      - 5432:5432
    networks:
      - task
    logging:
      driver: journald
      options:
        tag: "{{.Name}}"

  web:
    build: ./django
    command: uwsgi --ini /code/uwsgi.ini
    volumes:
      - ./django:/code
      - sock:/sock
#    ports:
#      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - task
    logging:
      driver: journald
      options:
        tag: "{{.Name}}"

  nginx:
    build: ./nginx
    volumes:
      - sock:/sock
      - ./django:/code
    ports:
      - 8000:8000
    networks:
      - task
    depends_on:
      - web
    logging:
      driver: journald
      options:
        tag: "{{.Name}}"

networks:
  task:

volumes:
  postgres_db:
  sock:
